# -*- coding: utf-8 -*-
"""beginner_portfolio_variance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWlpMAa-kgz9EKSHdNTLP47dZrzfZ2ZH
"""

import numpy as np

#assest weights and expected returns defined as vectors
weigths = np.array([0.565, 0.879])
expected_returns = np.array([0.058, 0.879])

#caluclate expected return using a dot product
portfolio_return = np.dot(weigths, expected_returns) * 100
print(f"portfolia return is {portfolio_return:.2f}%")


std = np.array([0.343, 0.56])

#correlation between assets
correlation = 0.4


convariance_matrix = np.array([
    [std[0]**2, correlation * std[0] * std[1]],
    [correlation * std[0] * std[1], std[1] ** 2]
])

#total variance of the portfolio usign matrix multiplication
portfolio_variance = np.dot(weigths, np.dot(convariance_matrix, weigths))
portfolio_std = np.sqrt(portfolio_variance)
print(f"the portflolia's standart deviation is {(portfolio_std * 100):.2f}%")